---
title: "Phthalates_ANOVA_SGAdjusted"
author: "Samantha Lapehn"
date: "2025-09-23"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Phthalates ANOVA

Here I will perform an ANOVA to look for differences by Trimester and Combined phthalates using the SG adjusted phthalates. 

### Load Packages
```{r load packages}
library(tidyverse)
```

### Load Data
Note: there is one participant in the GM data that was excluded from the T1 data since there were two T1 measurements. 
```{r load data}
T1 <- read.csv("/Volumes/paquette_a/GAPPSGrant_PrelimData/Sam/Data/RevisionUpdates/T1_NaturalLogPhthalates_N49_SGAdjusted_092325.csv")
T2 <- read.csv("/Volumes/paquette_a/GAPPSGrant_PrelimData/Sam/Data/RevisionUpdates/T2_NaturalLogPhthalates_N139_SGAdjusted_092325.csv")
T3 <- read.csv("/Volumes/paquette_a/GAPPSGrant_PrelimData/Sam/Data/RevisionUpdates/T3_NaturalLogPhthalates_N189_SGAdjusted_092325.csv")
GM <- read.csv("/Volumes/paquette_a/GAPPSGrant_PrelimData/Sam/Data/RevisionUpdates/Phthalate_CleanedLogData_GeoMean_LN_SGAdjusted_N222_092325.csv")
```

### Organize Data
```{r organize}
#Clean up GM Data
colnames(GM) <- toupper(colnames(GM))
names(GM)[names(GM) == 'DEHP2'] <- 'DEHP'
GM$Group <- c("GM")

#Clean up T1,2,3 Data
colnames(T1) <- toupper(colnames(T1))
names(T1)[names(T1) == 'DEHP2'] <- 'DEHP'
T1$Group <- c("T1")

colnames(T2) <- toupper(colnames(T2))
names(T2)[names(T2) == 'DEHP2'] <- 'DEHP'
T2$Group <- c("T2")

colnames(T3) <- toupper(colnames(T3))
names(T3)[names(T3) == 'DEHP2'] <- 'DEHP'
T3$Group <- c("T3")

#Combine Data
AllData <- rbind(GM, T1, T2, T3)
AllData <- AllData %>%
  dplyr::select(-X)

```

### One-Way ANOVA
```{r one-way}
cols <- setdiff(names(AllData), "Group")  # all columns except Group

results <- lapply(cols, function(col) {
  model <- aov(AllData[[col]] ~ AllData$Group)
  smry <- summary(model)[[1]]
  data.frame(
    Column = col,
    F_value = smry["AllData$Group", "F value"],
    p_value = smry["AllData$Group", "Pr(>F)"]
  )
})

# Combine into one table
results_table <- do.call(rbind, results)
results_table
```

